### ISSUE TITLE
Update Rspec dependency

### ISSUE THREAD

**Issue by johnhamelink** [developwithpassion/fakes-rspec#1]
Hey there,

I'm using this gem in my own gem - diplomat. Would you be able to upgrade the rspec dependency to 3.2.x so we can upgrade ours?

JH

**Comment by developwithpassion** [comment]
Hey John,

Sounds good. I'll take care of this tomorrow!

God Bless You,

JP

**Comment by johnhamelink** [comment]
Thanks!

—

**Comment by developwithpassion** [comment]
Hey John,

Gem updated to 2.1.0, now supports rspec 3+.

God Bless You,

JP

**Comment by johnhamelink** [comment]
Thank you for the update!

JH
